# ---------------------------------------------------------------
# DynamoDB — jobs
#
# Single table for both job types. Access patterns this schema supports:
#   1. Create a job                                    → PutItem (submitJob)
#   2. Get a job by ID                                 → GetItem (getJob, worker idempotency checks)
#   3. Update a job's status/result on completion       → UpdateItem (extractWorker, researchWorker)
#   4. Atomically decrement a research job's fan-in     → UpdateItem with ConditionExpression
#      counter when a source extraction completes         (extractWorker)
#
# No GSI — v1 only exposes GetItem-by-id (no "list jobs" endpoint), so a
# single-table point-lookup design is all this needs.
# ---------------------------------------------------------------

resource "aws_dynamodb_table" "jobs" {
  name         = "${local.prefix}-jobs"
  billing_mode = var.dynamodb_billing_mode
  hash_key     = "jobId"

  attribute {
    name = "jobId"
    type = "S"
  }

  point_in_time_recovery {
    enabled = true
  }

  server_side_encryption {
    enabled = true
  }
}

# Item schema (for reference — not enforced by DynamoDB):
#
# jobId                  (S) — PK, generated by submitJob
# type                   (S) — "extraction" | "research"
# status                 (S) — "queued" | "waiting" | "processing" | "succeeded" | "failed"
# input                  (M) — job-specific input (documentText/documentType, or companyName)
# result                 (M, when succeeded) — job-specific structured output
# error                  (S, when failed) — error message
# createdAt              (S) — ISO 8601 timestamp
# updatedAt              (S) — ISO 8601 timestamp
# inputTokens            (N)
# outputTokens           (N)
# estimatedCostUsd       (N)
# pendingExtractionCount (N, research jobs only) — present while status="waiting"; counts
#                             source extraction jobs this research job is fanned out over
# sourceExtractionJobIds (L of S, research jobs only) — jobIds of the source extraction jobs
# parentResearchJobId    (S, extraction jobs only) — set when this extraction was submitted
#                             as part of a research job's fan-out, so on completion it knows
#                             which parent's pendingExtractionCount to decrement
